services:
  web:
    build: .
    container_name: deal_web_app
    # entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    command: gunicorn project.wsgi:application --bind 0.0.0.0:14003 --timeout 600 --workers 4
    ports:
      - "14003:14003"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  worker:
    build: .
    container_name: deal_celery_worker
    command: celery -A project worker --loglevel=info
    ports:
      - "14101:14101"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  beat:
    build: .
    container_name: deal_celery_beat
    command: celery -A project beat --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  redis:
    image: redis:7-alpine
    container_name: deal_redis_deal_detector
    ports:
      - "6303:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
